### ISSUE TITLE
Port to .NET Framework

### ISSUE THREAD

**Issue by XenocodeRCE** [Zaczero/CloudflareSolver#1]
Tittle says it all

Would be very nice

**Comment by Zaczero** [comment]
.NET Standard is a standard which works with multiple platforms at once (.NET Framework, .NET Core, Mono etc. etc.). This library is compiled with .NET Standard 2.0 which works fine with **.NET Framework 4.6.1 or newer**.

Full specs:
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by Zaczero** [comment]
@XenocodeRCE So can we close that now 😋?

**Comment by XenocodeRCE** [comment]
Sure ; its not compatible for win XP but ok, i'll port it once i got time ; its only for httpclienthandler
