### ISSUE TITLE
Linux Jint

### ISSUE THREAD

**Issue by ElijahDD** [Zaczero/CloudflareSolver#4]
Hello.
How can i install jint and other dependency in linux? Or how can i replace Jint function with JS execute..

**Comment by Zaczero** [comment]
All you have to do to make it work on Linux is download the [release package](https://github.com/Zaczero/CloudflareSolver/releases/latest) and put all the files in single directory. Make sure you have installed dotnet. To replace Jint function change that code: https://github.com/Zaczero/CloudflareSolver/blob/59edba7a471af435e93b91b6e5ef6911d61dac3c/CloudflareSolver/CloudflareSolver.cs#L44

**Comment by ElijahDD** [comment]
> All you have to do to make it work on Linux is download the [release package](https://github.com/Zaczero/CloudflareSolver/releases/latest) and put all the files in single directory. Make sure you have installed dotnet. To replace Jint function change that code:
> 
> [CloudflareSolver/CloudflareSolver/CloudflareSolver.cs](https://github.com/Zaczero/CloudflareSolver/blob/59edba7a471af435e93b91b6e5ef6911d61dac3c/CloudflareSolver/CloudflareSolver.cs#L44)
> 
> Line 44 in [59edba7](/Zaczero/CloudflareSolver/commit/59edba7a471af435e93b91b6e5ef6911d61dac3c)
> 
>  private static double ExecuteJavaScript(string script)

All works, thx:)
another question: hidden html not found < on many sites with UAM enabled, why? Even on my site without any cloudflare settings (all default, only uam enabled), can i send some example site for you?

**Comment by Zaczero** [comment]
Sure, send me the example and I'll debug jt

**Comment by ElijahDD** [comment]
> Sure, send me the example and I'll debug it

I sent a email, thanks for the help, I will wait for a response with the result ;3

**Comment by Zaczero** [comment]
I received the email. I'll do those tests tomorrow :p
