### ISSUE TITLE
Using Cf.Solve Synchronous

### ISSUE THREAD

**Issue by KisaraTendo** [Zaczero/CloudflareSolver#5]
Hi, i'm having issues with your Library. Whenever i try to use it synchronously in my parallel, it won't solve the Cloudflare challenge and just stays stuck. However it does work when i'm using it in my parallel async

code (not working): var result = cf.Solve(client, HttpClientHandler, uri).Result;

Code (working): var result = await cf.Solve(client, HttpClientHandler, uri);

**Comment by Zaczero** [comment]
Try executing it like that: https://github.com/Zaczero/2Captcha/blob/master/2Captcha.Test/Program.cs
Make an async function and then execute the function like Foo().GetAwaiter().GetResult();

I'm pretty sure it's not the library's bug but rather how c# handles async on different machines.
https://stackoverflow.com/questions/17248680/await-works-but-calling-task-result-hangs-deadlocks

Alternatively try using .ConfigureAwait(false).Result;

**Comment by KisaraTendo** [comment]
I will try to use .ConfigureAwait(false).Result;, but making my parallel async and only awaiting the cf.solve works aswell. I will see what works better for me. Thanks
